name: Downloader Docker Image Build

on:
  workflow_dispatch:

jobs:
  aria2:
    name: Build Aria2
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - 
        name: Buildx
        uses: docker/build-push-action@v3
        with:
          context: downloader/aria2
          file: downloader/aria2/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/nas-tools-all-in-one:aria2-${{ steps.date.outputs.today }}

  qbittorrent:
    name: Build qBittorrent
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - 
        name: Buildx
        uses: docker/build-push-action@v3
        with:
          context: downloader/qbittorrent
          file: downloader/qbittorrent/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/nas-tools-all-in-one:qbittorrent-${{ steps.date.outputs.today }}

  qbittorrent_skip_patch:
    name: Build qBittorrent_Skip_Patch
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - 
        name: Buildx
        uses: docker/build-push-action@v3
        with:
          context: downloader/qbittorrent_skip_patch
          file: downloader/qbittorrent_skip_patch/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/nas-tools-all-in-one:qbittorrent_skip_patch-${{ steps.date.outputs.today }}

  transmission:
    name: Build Transmission
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - 
        name: Buildx
        uses: docker/build-push-action@v3
        with:
          context: downloader/transmission
          file: downloader/transmission/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/nas-tools-all-in-one:transmission-${{ steps.date.outputs.today }}

  transmission_skip_patch:
    name: Build Transmission_Skip_Patch
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
        
      - 
        name: Buildx
        uses: docker/build-push-action@v3
        with:
          context: downloader/transmission_skip_patch
          file: downloader/transmission_skip_patch/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/nas-tools-all-in-one:transmission_skip_patch-${{ steps.date.outputs.today }}